export const shareOverviewDialogTestIds = {
  root: "ShareOverviewDialog.root",
  heading: "ShareOverviewDialog.heading",
  status: "ShareOverviewDialog.status",
  link: "ShareOverviewDialog.link",
  shared: "ShareOverviewDialog.shared",
  private: "ShareOverviewDialog.private",
  createButton: "ShareOverviewDialog.createButton",
  copyButton: "ShareOverviewDialog.copyButton",
  systemShareButton: "ShareOverviewDialog.systemShareButton",
  editedNotice: "ShareOverviewDialog.editedNotice",
  updateButton: "ShareOverviewDialog.updateButton",
  stopButton: "ShareOverviewDialog.stopButton",
  confirmStopButton: "ShareOverviewDialog.confirmStopButton",
  keepSharingButton: "ShareOverviewDialog.keepSharingButton",
  signInButton: "ShareOverviewDialog.signInButton",
  cancelButton: "ShareOverviewDialog.cancelButton",
  doneButton: "ShareOverviewDialog.doneButton",
  closeButton: "ShareOverviewDialog.closeButton",
  failure: "ShareOverviewDialog.failure",
};
