export const overviewActionsMenuTestIds = {
  root: "OverviewActionsMenu.root",
  trigger: "OverviewActionsMenu.trigger",
  menu: "OverviewActionsMenu.menu",
  editTopicsItem: "OverviewActionsMenu.editTopicsItem",
  topicCount: "OverviewActionsMenu.topicCount",
  reasonItem: "OverviewActionsMenu.reasonItem",
  readItem: "OverviewActionsMenu.readItem",
  watchItem: "OverviewActionsMenu.watchItem",
  shareItem: "OverviewActionsMenu.shareItem",
  copyLinkItem: "OverviewActionsMenu.copyLinkItem",
  openInWebItem: "OverviewActionsMenu.openInWebItem",
  openInWebReason: "OverviewActionsMenu.openInWebReason",
  deleteItem: "OverviewActionsMenu.deleteItem",
};
