export const queuePageTestIds = {
  root: "QueuePage.root",
  heading: "QueuePage.heading",
  backLink: "QueuePage.backLink",
  pauseButton: "QueuePage.pauseButton",
  resumeButton: "QueuePage.resumeButton",
  clearButton: "QueuePage.clearButton",
  clearConfirm: "QueuePage.clearConfirm",
  confirmClearButton: "QueuePage.confirmClearButton",
  keepButton: "QueuePage.keepButton",
  noKeyNote: "QueuePage.noKeyNote",
  heldNote: "QueuePage.heldNote",
  addKeyLink: "QueuePage.addKeyLink",
  making: "QueuePage.making",
  waiting: "QueuePage.waiting",
  waitingLabel: "QueuePage.waitingLabel",
  attention: "QueuePage.attention",
  attentionLabel: "QueuePage.attentionLabel",
  empty: "QueuePage.empty",
};
