export const readerPlayerBarTestIds = {
  root: "ReaderPlayerBar.root",
  skipBackButton: "ReaderPlayerBar.skipBackButton",
  playButton: "ReaderPlayerBar.playButton",
  skipForwardButton: "ReaderPlayerBar.skipForwardButton",
  rateButton: "ReaderPlayerBar.rateButton",
  favouriteButton: "ReaderPlayerBar.favouriteButton",
  label: "ReaderPlayerBar.label",
  pacerTag: "ReaderPlayerBar.pacerTag",
  clock: "ReaderPlayerBar.clock",
  signInLink: "ReaderPlayerBar.signInLink",
  voiceLink: "ReaderPlayerBar.voiceLink",
  reRecordButton: "ReaderPlayerBar.reRecordButton",
  reRecordInline: "ReaderPlayerBar.reRecordInline",
  action: (action: string) => `ReaderPlayerBar.action.${action}`,
};
