export const transcriptPanelTestIds = {
  root: "TranscriptPanel.root",
  sourceNote: "TranscriptPanel.sourceNote",
  skeleton: "TranscriptPanel.skeleton",
  emptyNote: "TranscriptPanel.emptyNote",
  errorNote: "TranscriptPanel.errorNote",
  tools: "TranscriptPanel.tools",
  copyButton: "TranscriptPanel.copyButton",
  exportButton: "TranscriptPanel.exportButton",
  searchInput: "TranscriptPanel.searchInput",
  matchCount: "TranscriptPanel.matchCount",
  previousMatchButton: "TranscriptPanel.previousMatchButton",
  nextMatchButton: "TranscriptPanel.nextMatchButton",
  match: "TranscriptPanel.match",
  followingNote: "TranscriptPanel.followingNote",
  followButton: "TranscriptPanel.followButton",
  row: "TranscriptPanel.row",
  rowTime: "TranscriptPanel.rowTime",
  rowText: "TranscriptPanel.rowText",
  speakerMark: "TranscriptPanel.speakerMark",
};
