export const transcriptPanelTestIds = {
  root: "TranscriptPanel.root",
  head: "TranscriptPanel.head",
  sourceNote: "TranscriptPanel.sourceNote",
  skeleton: "TranscriptPanel.skeleton",
  emptyNote: "TranscriptPanel.emptyNote",
  errorNote: "TranscriptPanel.errorNote",
  retryButton: "TranscriptPanel.retryButton",
  tools: "TranscriptPanel.tools",
  copyButton: "TranscriptPanel.copyButton",
  exportButton: "TranscriptPanel.exportButton",
  searchInput: "TranscriptPanel.searchInput",
  matchCount: "TranscriptPanel.matchCount",
  clearSearchButton: "TranscriptPanel.clearSearchButton",
  previousMatchButton: "TranscriptPanel.previousMatchButton",
  nextMatchButton: "TranscriptPanel.nextMatchButton",
  match: "TranscriptPanel.match",
  followingNote: "TranscriptPanel.followingNote",
  notFollowingNote: "TranscriptPanel.notFollowingNote",
  followButton: "TranscriptPanel.followButton",
  backToChaptersButton: "TranscriptPanel.backToChaptersButton",
  chapterChip: "TranscriptPanel.chapterChip",
  playingBadge: "TranscriptPanel.playingBadge",
  row: "TranscriptPanel.row",
  rowTime: "TranscriptPanel.rowTime",
  rowText: "TranscriptPanel.rowText",
  speakerMark: "TranscriptPanel.speakerMark",
};
