export const readerMastheadTestIds = {
  root: "ReaderMasthead.root",
  backLink: "ReaderMasthead.backLink",
  breadcrumb: "ReaderMasthead.breadcrumb",
  previousLink: "ReaderMasthead.previousLink",
  nextLink: "ReaderMasthead.nextLink",
  position: "ReaderMasthead.position",
  published: "ReaderMasthead.published",
  title: "ReaderMasthead.title",
  channel: "ReaderMasthead.channel",
  meta: "ReaderMasthead.meta",
  readButton: "ReaderMasthead.readButton",
  readAloudButton: "ReaderMasthead.readAloudButton",
  listenButton: "ReaderMasthead.listenButton",
};
