export const syncPanelTestIds = {
  root: "SyncPanel.root",
  apiUrlInput: "SyncPanel.apiUrlInput",
  emailInput: "SyncPanel.emailInput",
  requestLinkButton: "SyncPanel.requestLinkButton",
  linkSent: "SyncPanel.linkSent",
  changeAddressButton: "SyncPanel.changeAddressButton",
  codeInput: "SyncPanel.codeInput",
  connectButton: "SyncPanel.connectButton",
  formError: "SyncPanel.formError",
  signedInAs: "SyncPanel.signedInAs",
  statusLine: "SyncPanel.statusLine",
  syncNowButton: "SyncPanel.syncNowButton",
  signOutButton: "SyncPanel.signOutButton",
};
