export const capturePageTestIds = {
  root: "CapturePage.root",
  opening: "CapturePage.opening",
  createButton: "CapturePage.createButton",
  readOverviewButton: "CapturePage.readOverviewButton",
  createAgainButton: "CapturePage.createAgainButton",
  alreadyInLibraryNote: "CapturePage.alreadyInLibraryNote",
  noVideoNote: "CapturePage.noVideoNote",
  captionsNote: "CapturePage.captionsNote",
  keysNote: "CapturePage.keysNote",
  settingsLink: "CapturePage.settingsLink",
  working: "CapturePage.working",
  workingTitle: "CapturePage.workingTitle",
  workingChannel: "CapturePage.workingChannel",
  elapsed: "CapturePage.elapsed",
  cancelButton: "CapturePage.cancelButton",
  startAgainButton: "CapturePage.startAgainButton",
  keepOpenNote: "CapturePage.keepOpenNote",
  error: "CapturePage.error",
};
