export const manageTagsDialogTestIds = {
  root: "ManageTagsDialog.root",
  summary: "ManageTagsDialog.summary",
  closeButton: "ManageTagsDialog.closeButton",
  notice: "ManageTagsDialog.notice",
  undoButton: "ManageTagsDialog.undoButton",
  searchInput: "ManageTagsDialog.searchInput",
  sortOption: (sort: string) => `ManageTagsDialog.sortOption.${sort}`,
  list: "ManageTagsDialog.list",
  row: (tag: string) => `ManageTagsDialog.row.${tag}`,
  empty: "ManageTagsDialog.empty",
  renameButton: "ManageTagsDialog.renameButton",
  mergeButton: "ManageTagsDialog.mergeButton",
  deleteButton: "ManageTagsDialog.deleteButton",
  clearButton: "ManageTagsDialog.clearButton",
  renameRow: "ManageTagsDialog.renameRow",
  renameInput: "ManageTagsDialog.renameInput",
  renameStatus: "ManageTagsDialog.renameStatus",
  saveRenameButton: "ManageTagsDialog.saveRenameButton",
  backButton: "ManageTagsDialog.backButton",
  keepOption: (tag: string) => `ManageTagsDialog.keepOption.${tag}`,
  newNameInput: "ManageTagsDialog.newNameInput",
  mergeSummary: "ManageTagsDialog.mergeSummary",
  confirmMergeButton: "ManageTagsDialog.confirmMergeButton",
};
